<a href="https://colab.research.google.com/github/aditya-singh-231/pytorch-campusx/blob/main/pytorch_training_pipeline_improved_L5_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this I have used 'nn' module for creating the model, used built in activation functions, used built in loss funtions, and used built in optimizers, unlike the previous model made where everything is coded and no modules or inbuilt functions, optimizers are used.

In [ ]:
#import the reqd. libraries
import torch
import torch.nn as nn

# creating a model class


"""
#normal code

class Model(nn.Module):
  def __init__(self, num_features): # num_features will tell the no. of fearures in our input
    super().__init__()
    self.linear=nn.Linear(num_features, 1) #we have to get only 1 output
    self.sigmoid=nn.Sigmoid()

  def forward(self, features):   # features are the data that we are inputting in the model
    out=self.linear(features)    #here we are calculating 'z=wx+b', here 'out' is our 'z'
    out=self.sigmoid(out)
    return out

"""


"""
#improved code 1 (using hidden layers)

# now we are building a model with hidden layers
class Model(nn.Module):
  # in constructor we will define the structure of our neural network
  def __init__(self, num_features): # num_features will tell the no. of fearures in our input
    super().__init__()
    self.linear1=nn.Linear(num_features, 3)
    self.relu=nn.ReLU()
    self.linear2=nn.Linear(3,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self, features):

    out=self.linear1(features)
    out=self.relu(out)
    out=self.linear2(out)
    out=self.sigmoid(out)
    return out

  """

  # improved code 2 (using containers (Sequential))

class Model(nn.Module):
    # in constructor we will define the structure of our neural network
  def __init__(self, num_features): # num_features will tell the no. of fearures in our input
    super().__init__()
    self.network=nn.Sequential(
      nn.Linear(num_features,3),
      nn.ReLU(),
      nn.Linear(3,1),
      nn.Sigmoid()
    )

  def forward(self, features):
    out=self.network(features)
    return out

In [ ]:
#create dataset
features=torch.rand(10,5) # a dataset with 10 rows and 5 columns--- 5 columns because we have 5 features

#create a model
model=Model(features.shape[1])  # the value of features.shape[1] is 5

#call model for forward pass
model(features)  # we can also do 'model.forward(features)', but the prev. one is recommended by'PyTorch'

# whenever we call the object of the 'Model' class, then automatically 'forward' method of this class is called. PyTorch has overwritten the '__call__' method in 'nn.Module' class for this thing.


tensor([[0.3923],
        [0.3854],
        [0.3900],
        [0.3813],
        [0.3758],
        [0.3839],
        [0.3815],
        [0.3906],
        [0.3829],
        [0.3917]], grad_fn=<SigmoidBackward0>)

in the above o/p we got, we did not did backpropagation, all we did was sending the rows and getting the corresponding y_pred

In [ ]:
#show model weights
"""model.linear.weight   # as we have 5 features and using only 1 neuron we will only 5 weigths
"""

"""
model.linear1.weight
"""

model.network[0].weight

Parameter containing:
tensor([[ 0.0796,  0.3682,  0.3161,  0.0205,  0.3571],
        [-0.1152,  0.1491, -0.2255, -0.3999, -0.2111],
        [ 0.0952, -0.3324, -0.3036,  0.0287,  0.1574]], requires_grad=True)

In [ ]:
model.network[0].bias

Parameter containing:
tensor([-0.0961,  0.0251, -0.0210], requires_grad=True)

To visualize the whole workflow we did above we need a library 'torchinfo'

In [ ]:
!pip install torchinfo  # installing the 'torchinfo' library

In [ ]:
from torchinfo import summary
summary(model, input_size=(10,5))   # we will get our model summary--- the number of parameters, the layers, the shape of layers.

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00